### ISSUE TITLE
Adjust screen reader class to use more modern syntax

### ISSUE THREAD

**Issue by JacobDB** [JacobDB/new-site#207]
via https://www.scottohara.me/blog/2017/04/14/inclusively-hidden.html:

```css
.sr-only:not(:focus):not(:active) {
  clip: rect(0 0 0 0); 
  clip-path: inset(100%);
  height: 1px;
  overflow: hidden;
  position: absolute;
  white-space: nowrap; 
  width: 1px;
}
```
